// SEC-01: the Content-Security-Policy builder and the static security-header
// list — the single source of truth for every security response header this
// app ships.
//
// Split of responsibilities (04-CONTEXT.md D4-07):
// - The CSP is built here but *applied* by `src/proxy.ts`, because it embeds a
//   per-request nonce and a static `next.config.ts` header cannot carry one.
//   The no-nonce alternative in Next's own docs requires
//   `script-src 'unsafe-inline'` — the exact thing SEC-01 forbids.
// - `staticSecurityHeaders` is applied by `next.config.ts` `headers()`,
//   because those values are per-deployment constants: recomputing them per
//   request in the proxy would buy nothing, and `headers()` also covers paths
//   the proxy matcher skips (static assets, prefetches).
//
// This module is pure on purpose: `src/lib/csp.test.ts` pins the policy shape
// so that any future loosening — above all, `unsafe-inline` creeping into
// script-src — fails a named test instead of shipping silently (T-04-06).

/**
 * Build the Content-Security-Policy for one request.
 *
 * @param nonce - the per-request nonce generated by `src/proxy.ts`. Next
 *   extracts it from the CSP header and applies it to framework scripts,
 *   bundles, and its own inline scripts automatically.
 * @param isDev - development mode. The ONLY difference it makes is
 *   `'unsafe-eval'` on script-src: React uses `eval` in development to
 *   reconstruct server-side error stacks in the browser. Neither React nor
 *   Next.js uses `eval` in production, so production must not carry it.
 */
export function buildCsp(nonce: string, isDev: boolean): string {
  const directives = [
    // Fallback for every fetch the browser makes that no directive below
    // names — including the RSC/navigation fetches, which are same-origin.
    // No connect-src for api.github.com: all GitHub traffic is server-side,
    // and the CSP governs the browser.
    "default-src 'self'",
    // 'strict-dynamic': trust propagates from the nonce'd bootstrap scripts
    // to the scripts they load, so Next's chunk loading works without
    // enumerating hashes. Never 'unsafe-inline' — that is the SEC-01 line
    // that does not move (D4-05).
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic'${
      isDev ? " 'unsafe-eval'" : ""
    }`,
    // D4-06 ladder rung 1: the strict nonce form. Stepped only on measured
    // violation evidence (e2e/security-headers.spec.ts), and any step is
    // reflected back into the unit tests — never into script-src.
    `style-src 'self' 'nonce-${nonce}'`,
    // 'self' covers the `/_next/image` optimizer output; the avatar host
    // covers direct avatar loads; data: covers inline placeholder images.
    "img-src 'self' data: https://avatars.githubusercontent.com",
    "font-src 'self'",
    // No plugins, ever.
    "object-src 'none'",
    // An injected <base> tag must not be able to redirect relative URLs.
    "base-uri 'self'",
    // The search form submits to this origin only.
    "form-action 'self'",
    // Belt to X-Frame-Options' braces: frame-ancestors is the modern control,
    // X-Frame-Options (in staticSecurityHeaders) covers older UAs.
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
  ];
  return directives.join("; ");
}

export type SecurityHeader = { key: string; value: string };

/**
 * The per-deployment-constant security headers, applied for every path by
 * `next.config.ts` `headers()` (D4-07). The CSP is deliberately NOT here —
 * it carries a per-request nonce and lives in `src/proxy.ts`.
 */
export const staticSecurityHeaders: readonly SecurityHeader[] = [
  // Never MIME-sniff a response into something executable (T-04-09).
  { key: "X-Content-Type-Options", value: "nosniff" },
  // Search terms live in the URL by design (URL is state); this stops full
  // URLs — keyword included — leaking to third-party origins (T-04-07).
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  // Legacy-UA counterpart of frame-ancestors 'none' (T-04-08).
  { key: "X-Frame-Options", value: "DENY" },
  // Meaningful only once served over HTTPS from a real domain — a plain-HTTP
  // localhost response carries it inertly (browsers ignore HSTS on HTTP).
  {
    key: "Strict-Transport-Security",
    value: "max-age=31536000; includeSubDomains",
  },
];
